### ISSUE TITLE
TypeError: Cannot read property 'error' of null

### ISSUE THREAD

**Issue by andreasasprou** [recurly/recurly-client-node#51]
**Describe the bug**

401 error codes not handled by `BaseClient.js`

```javascript
const client =  new recurly.Client(apiKey);
await this.client.listPlans({ limit: 2 }).count();
```

TypeError: Cannot read property 'error' of null

    at IncomingMessage.<anonymous> (/Users/XYZ/node_modules/recurly/lib/recurly/BaseClient.js:71:50)
    at IncomingMessage.emit (events.js:215:7)
    at endReadableNT (_stream_readable.js:1183:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)

```
// BaseCleint.js

const recurlyResponse = new Response(httpResponse, rbody, recurlyRequest)

/*
recurlyResponse = Response {
      request: Request { method: 'HEAD', path: '/plans?limit=2', body: null },
      body: null, <---- Body is null with this 401 error
      status: 401,
      requestId: '528928cb49dbe604-LHR',
      rateLimit: NaN,
      rateLimitRemaining: NaN,
      rateLimitReset: Invalid Date,
      recordCount: null,
      date: 'Sun, 20 Oct 2019 07:08:14 GMT',
      proxyMetadata: { server: 'cloudflare', 'cf-ray': '528928cb49dbe604-LHR' }
    }
*/

if (recurlyResponse.status < 200 || recurlyResponse.status > 299) {
    const errBody = recurlyResponse.body.error // <--- HERE

// ...rest
```

**To Reproduce**

```javascript
const client =  new recurly.Client(apiKey);
await this.client.listPlans({ limit: 2 }).count();
```

**Expected behavior**

To display a useful 401 error

**Comment by bhelx** [comment]
@andreasasprou Thanks for another very well described issue. It helps me reproduce the problem really quickly. The problem appears to be with `HEAD` request (on the `count` call. Seems to to  work fine for other responses with a body:

```
UnauthorizedError [RecurlyUnauthorizedError]: Invalid API key
    at IncomingMessage.<anonymous> (/app/clients/node/lib/recurly/BaseClient.js:73:25)
    at IncomingMessage.emit (events.js:214:15)
    at endReadableNT (_stream_readable.js:1178:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  name: 'RecurlyUnauthorizedError',
  type: 'unauthorized',
  params: []
}
```

 I will change the response handler in the `BaseClient`to be more resilient to responses with no body tomorrow.
